[package]
name = "leetcode-2020-06-13"
version = "0.1.0"
authors = ["William Marsman <william.marsman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simplelog = "^0.7.6"
log = "^0.4"
